---
title: "Comparison graph"
author: "AnnaClaire Marley"
date: "3/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

```
County Area df
```{r}
ca_profile<-read_csv("ca_profile.csv")

county_area<-ca_profile %>%
  mutate(area=total_area_sqml) %>% 
  select(county, area) 
```

Health:

```{r}
health <- read_csv("health_rank_ca.csv")

# health ranks
healh <- health %>% 
  select(county, rank) %>% 
  rename(health_rank = rank)
```

Recreation:
```{r}
recreation <- read_csv("recreation_ca.csv")

rec_df<-merge(county_area, recreation, by="county")


# recreation ranks
rec <- rec_df %>% 
  mutate(rec_area = est/area) %>% 
  arrange(-rec_area) %>% 
  mutate(rec_rank=c(1:58)) %>% 
  select(county, rec_area, rec_rank)
```


Diversity:
```{r}

diversity <- read_csv("ca_profile.csv")

# diversity ranks
div <- diversity %>% 
  select(county, div_index) %>% 
  arrange(-div_index) %>% 
  mutate(div_rank = c(1:58)) %>% 
  arrange(county)


```

Entertainment

```{r}

entertainment <- read_csv("entertainment_ca.csv")

entertainment<-merge(entertainment, county_area, by = "county")

# entertainment ranks
ent <- entertainment %>% 
  mutate(estab_area = est/area) %>% 
  arrange(-estab_area) %>% 
  mutate(ent_rank = c(1:58)) %>% 
  select(county, estab_area, ent_rank) %>% 
  arrange(county)



```

Nightlife
```{r}

night_life <- read_csv("night_life_ca.csv")
night_life<-merge(night_life, county_area, "county") #merging to add area. this way, we know for sure that the area corresponds to the county. 


night_norm <- night_life %>% 
  rename(establishment = est) %>% 
  mutate(drink_area = establishment/area) %>% 
  select(county, drink_area) %>% 
  arrange(-drink_area) %>% 
  mutate(night_rank = c(1:58)) 


```


Merging Rank and Values/ making percentile 

```{r}
master_ranks <- read_csv("master_ranks.csv")

master_percentile<-master_ranks %>% 
  select(-X1) %>% 
  gather(category, rank, -county) %>% 
  mutate(percentile= 1-rank/58)
```


Master data frame with ranks and values
```{r}


master <- ent %>% 
  mutate(div_index = div$div_index) %>% 
  mutate(div_rank = div$div_rank) %>% 
  mutate(rec_area = rec$rec_area) %>% 
  mutate(rec_rank = rec$rec_rank) %>% 
  mutate(health_rank = heal$health_rank) %>% 
  mutate(night_rank = night_norm$night_rank) %>% 
  mutate(night_area = night_norm$drink_area) %>% 
  mutate(ent_area = ent$estab_area) %>% 
  mutate(ent_rank = ent$estab_rank)

master_ranks <- master %>% 
  select(county, div_rank, rec_rank, health_rank, night_rank, ent_rank) 

master_value <- master %>% 
  select(county, estab_area, div_index, rec_area, health_rank, night_area, ent_area)

write.csv(master_value,'master_value.csv')

write.csv(master_ranks,'master_ranks.csv')
  
```

Trial graph

```{r}

master_tidy <- read_csv("master_tidy.csv") %>% 
  select(county, rank, rank_name)

compare_graph <- master_tidy %>% 
  filter( county == "San Francisco" | county == "Santa Clara") %>% 
  ggplot(aes(x = rank_name, y = rank)) +
  geom_col(aes(fill = county), position = "dodge") +
  scale_y_continuous(expand = c(0,0)) +
  labs(
    x = "Type",
    y = "Rank"
  ) +
  coord_flip() +
  theme_bw()

compare_graph

```

Bar graph percentiles
```{r}

master_tidy <- read_csv("master_tidy.csv") %>% 
  select(county, rank, rank_name)

compare_graph2 <- master_percentile %>% 
  filter( county == "San Francisco" | county == "Santa Clara") %>% 
  ggplot(aes(x = category, y = percentile)) +
  geom_col(aes(fill = county), position = "dodge") +
  scale_y_continuous(expand = c(0,0), limits = c(0,1)) +
  labs(
    x = "Type",
    y = "Percentile"
  ) +
  coord_flip() +
  theme_bw()

compare_graph2

```





```{r}
library(plotly)
library(RColorBrewer)
library(viridis)


master_ranks2 <- read_csv("master_ranks2.csv")

just_2 <- master_ranks2 %>% 
  filter(county == "Alameda" | county == "Alpine") %>% 
 dplyr::select(-X1)


paralell_graph <- just_2 %>%
  plot_ly(type = 'parcoords',
          line = list(color = ~county),
          text = ~paste('County', county),
          dimensions = list(
            list(range = c(58,1),
                 label = 'Entertainment', values = ~ent_rank),
            list(range = c(58,1),
                 constraintrange = c(5,6),
                 label = 'Night life', values = ~night_rank),
            list(range = c(58,1),
                 label = 'Recreation', values = ~rec_rank),
            list(range = c(58,1),
                 label = 'Health', values = ~health_rank),
            list(range = c(58,1),
                 label = 'Diversity', values = ~div_rank)
            )
          )

paralell_graph

```



```{r}

options(viewer=NULL) 

df <- read.csv("https://raw.githubusercontent.com/bcdunbar/datasets/master/iris.csv")   
p <- df %>%
  plot_ly(type = 'parcoords',
          line = list(color = ~species_id,
                      colorscale = list(c(0,'red'),c(0.5,'green'),c(1,'blue'))),
          dimensions = list(
            list(range = c(2,4.5),
                 label = 'Sepal Width', values = ~sepal_width),
            list(range = c(4,8),
                 constraintrange = c(5,6),
                 label = 'Sepal Length', values = ~sepal_length),
            list(range = c(0,2.5),
                 label = 'Petal Width', values = ~petal_width),
            list(range = c(1,7),
                 label = 'Petal Length', values = ~petal_length)
          )
   )

p
```


