---
title: "ESM 224 Final Project"
author: "Sara Orofino"
date: "2/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
```

County names vector for easier future use:
```{r}
# Create a vector of names for  counties  

county_names <- c("Alameda", "Alpine", "Amador", "Butte", "Calaveras", "Colusa",
                                     "Contra Costa", "Del Norte","El Dorado", "Fresno", "Glenn",
                                     "Humbolt", "Imperial", "Inyo", "Kern",  "Kings", "Lake", 
                                     "Lassen", "Los Angeles", "Madera", "Marin", "Mariposa", 
                                     "Mendocino", "Merced", "Modoc", "Mono", "Monterey", "Napa",
                                     "Nevada", "Orange", "Placer", "Plumas", "Riverside", "Sacramento",
                                     "San Benito", "San Bernadino", "San Diego", "San Francisco", 
                                     "San Joaquin", "San Louis Obispo", "San Mateo", "Santa Barbara",
                                     "Santa Clara", "Santa Cruz", "Shasta",  "Sierra", "Siskiyou", 
                                     "Solano", "Sonoma", "Stanislaus", "Sutter", "Tehama",
                                     "Trinity", "Tulare", "Tuolumne", "Ventura", "Yolo", "Yuba")

county_names_df <- as.data.frame(county_names)
```

California county population for the year 2018

```{r}

pop_2019 <- read_csv("ca_county_2019_pop.csv") %>% 
  clean_names() %>% 
  rename(county = name) %>% 
  rename(pop_19 = x2019_population) %>% 
  arrange(county) %>% 
  add_column(county_names) %>% 
  select(county_names, pop_19) %>% 
  rename(county = county_names) 

```


Analyzing the different datasets to determine the best threshold values to choose

```{r}
### nightlife exploration
night_life <- read_csv("night_life.csv")

# number of drinking establishments per capita
night_percap <- merge(night_life, pop_2019, by = c("county")) %>% 
  mutate(nightpc = drinking_establish/pop_19)
  
  
  
## histograms
rice <- 2*((NROW(night_life$drinking_establish))^(1/3))

night_hist <- night_life %>% 
  ggplot(aes(x = drinking_establish)) +
  geom_histogram() +
   scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme_minimal()
night_hist

median(night_life$drinking_establish) #16
mean(night_life$drinking_establish) # 56

# health
health <- read_csv()

```



Testing out spatial analysis for the map for Shiny Output 1
```{r sf, echo=FALSE, warning=FALSE}

# load packages

library(sf)

# read in data

ca_counties <- st_read(dsn = "CA_Counties", layer = "CA_Counties_TIGER2016")

# Create a basemap of CA counties for output 1 

ca_basemap <- ca_counties %>% 
  select(COUNTYFP)

plot(ca_basemap)

```

