---
title: "Final Code"
author: "Sara Orofino"
date: "3/1/2019"
output: html_document
---
**Final Code for graphs - run this markdown before launching the app**  

Packages:  
```{r}

library(tidyverse)
library(kableExtra)

```

County Names for App Selection:  
```{r}
county_names <- c("Alameda", "Alpine", "Amador", "Butte", "Calaveras", "Colusa",
                                     "Contra Costa", "Del Norte","El Dorado", "Fresno", "Glenn",
                                     "Humbolt", "Imperial", "Inyo", "Kern",  "Kings", "Lake", 
                                     "Lassen", "Los Angeles", "Madera", "Marin", "Mariposa", 
                                     "Mendocino", "Merced", "Modoc", "Mono", "Monterey", "Napa",
                                     "Nevada", "Orange", "Placer", "Plumas", "Riverside", "Sacramento",
                                     "San Benito", "San Bernadino", "San Diego", "San Francisco", 
                                     "San Joaquin", "San Louis Obispo", "San Mateo", "Santa Barbara",
                                     "Santa Clara", "Santa Cruz", "Shasta",  "Sierra", "Siskiyou", 
                                     "Solano", "Sonoma", "Stanislaus", "Sutter", "Tehama",
                                     "Trinity", "Tulare", "Tuolumne", "Ventura", "Yolo", "Yuba")

```

Tab 2: 

```{r}




```


Tab 3:

```{r}
library(MASS)

# Create values data frame with CA average to feed into the table for Tab 3
div_avg <- mean(values_test$div_index)
rec_avg <- mean(values_test$rec_area)
night_avg <- mean(values_test$night_area)
ent_avg <- mean(values_test$ent_area)


new_row <- data.frame(county = 'CA Average', 
                      div_index = 0.516, 
                      rec_area = 0.352,
                      night_area = 0.175,
                      ent_area = 0.230,
                      health_rank = 'NA')


values <- read_csv("master_value.csv") %>%
  dplyr::select(county, div_index, rec_area, night_area, ent_area, health_rank) 

values <- rbind(values,new_row)

write.csv(values, 'values.csv', row.names = FALSE)


# Data frame needed for graph in tab 3
master_ranks <- read_csv("master_ranks.csv")

```

