---
title: "ESM 224 Final Project"
author: "Sara Orofino"
date: "2/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(kableExtra)

```

County names vector for easier future use:
```{r}
# Create a vector of names for  counties  

county_name_vector <- c("Alameda", "Alpine", "Amador", "Butte", "Calaveras", "Colusa",
                                     "Contra Costa", "Del Norte","El Dorado", "Fresno", "Glenn",
                                     "Humbolt", "Imperial", "Inyo", "Kern",  "Kings", "Lake", 
                                     "Lassen", "Los Angeles", "Madera", "Marin", "Mariposa", 
                                     "Mendocino", "Merced", "Modoc", "Mono", "Monterey", "Napa",
                                     "Nevada", "Orange", "Placer", "Plumas", "Riverside", "Sacramento",
                                     "San Benito", "San Bernadino", "San Diego", "San Francisco", 
                                     "San Joaquin", "San Louis Obispo", "San Mateo", "Santa Barbara",
                                     "Santa Clara", "Santa Cruz", "Shasta",  "Sierra", "Siskiyou", 
                                     "Solano", "Sonoma", "Stanislaus", "Sutter", "Tehama",
                                     "Trinity", "Tulare", "Tuolumne", "Ventura", "Yolo", "Yuba")

county_names <- as.data.frame(county_names)

write.csv(county_names, 'county_names.csv')
```

California county population for the year 2018

```{r}

pop_2019 <- read_csv("ca_county_2019_pop.csv") %>% 
  clean_names() %>% 
  rename(county = name) %>% 
  rename(pop_19 = x2019_population) %>% 
  arrange(county) %>% 
  add_column(county_names) %>% 
  select(county_names, pop_19) %>% 
  rename(county = county_names) 

```


Analyzing the different datasets to determine the best threshold values to choose

Nightlife:
```{r}
### nightlife exploration
night_life <- read_csv("night_life.csv")

# number of drinking establishments per capita
night_percap <- merge(night_life, pop_2019, by = c("county")) %>% 
  mutate(nightpc = drinking_establish/pop_19)
  
## histograms
rice <- 2*((NROW(night_life$drinking_establish))^(1/3))

night_hist <- night_percap %>% 
  ggplot(aes(x = nightpc)) +
  geom_histogram() +
   scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme_minimal()
night_hist

median(night_percap$nightpc) #  8.08157e-05
mean(night_percap$nightpc) # 0.0001124961

# top 5 greatest values for number of drinking establishments per capita
night_pc_5 <- night_percap %>%  
  arrange(-nightpc) %>% 
  head(5)

```

Health:

```{r}



```


Testing out spatial analysis for the map for Shiny Output 1
```{r sf, echo=FALSE, warning=FALSE}

# load packages

library(sf)

# read in data

ca_counties <- st_read(dsn = "CA_Counties", layer = "CA_Counties_TIGER2016")

# Create a basemap of CA counties for output 1 

ca_basemap <- ca_counties %>% 
  dplyr::select(NAME, COUNTYFP)

plot(ca_basemap)

# make basemap grey with black outlines of counties

county_outline <- ca_basemap %>% 
  ggplot() +
  geom_sf(fill = "NA",
          color = "gray30",
          show.legend = FALSE) +
  theme_minimal() +
  coord_sf(datum = NA) 

county_outline

```

Try to figure out inputs to make different counties appear

```{r}
# first try nightlife

nightlife_counties <- ca_basemap %>% 
  dplyr::filter(NAME == "Trinity" | NAME == "Plumas" | NAME == "San Francisco" | NAME == "Sierra" | NAME == "Mendocino")

# need to make this so that we just add whatever the input is from the app to the county outline so data = should be the input but then otherwise can keep this map
nl_county_map <- county_outline +
  geom_sf(data = nightlife_counties,
    aes(fill = NAME)) +
  theme_minimal() +
  coord_sf(datum = NA)

nl_county_map
```

Table for Tab 3 Comparison:
```{r}

# Filter for just two counties (to represent the two inputs) and select only the metrics that will show up in the graph:
values <- read_csv("master_value.csv") %>%
  dplyr::select(county, div_index, rec_area, night_area, ent_area, health_rank) 

## Kable table trial
values <- read_csv("values.csv")
comparison_table <- kable(values, col.names = c("County", "Attribute 2", "Diversity", "Recreation",
                                                "Nightlife", "Entertainment", "Health Rank"),
                          align = "c", digits = 3) %>% 
  kable_styling(bootstrap_options = c("striped", "hovered", "boardered"), full_width = F) %>% 
  column_spec(1, bold = T) %>% 
  add_header_above(c(" " = 2, "Number of Establishments per Area" = 4, " " = 1)) 

comparison_table

# Find the mean of all indexes for the CA average:

div_avg <- mean(values_test$div_index)
rec_avg <- mean(values_test$rec_area)
night_avg <- mean(values_test$night_area)
ent_avg <- mean(values_test$ent_area)

# Add a row the dataframe of the all CA averages:
add_row(values_test, 
        county = "CA Average", 
        div_index = 0.516, 
        rec_area = 0.352, 
        night_area = 0.175, 
        ent_area = 0.230)

# That was supposed to work but didn't...

library(MASS)
new_row <- data.frame(county = 'CA Average', 
                      div_index = 0.516, 
                      rec_area = 0.352,
                      night_area = 0.175,
                      ent_area = 0.230,
                      health_rank = 'NA')

values_test <- rbind(values_test,new_row)

# Try GT table 

library(gt)
values_test <- read_csv("values2.csv")

values_test %>% 
  dplyr::filter(county == "Santa Barbara" | county == "Amador" | county == "CA Average") %>% 
  gt() %>% 
  tab_header(
    title = md("**County Metrics Comparison**")
  ) %>% 
  cols_label(county = md("**County**"),
             div_index = md("**Diversity**"),
             rec_area = md("**Recreation**"),
             night_area = md("**Nightlife**"),
             ent_area = md("**Entertainment**"),
             health_rank = md("**Health Rank**")) %>% 
  tab_spanner(label = md("Number of Establishments per Area"), 
              columns = vars(div_index, rec_area, night_area, ent_area)) %>% 
  fmt_number(columns = vars(div_index, rec_area, night_area, ent_area),
    decimals = 3) %>% 
  tab_style(
    style = cells_styles(
      text_style = "italic",
      text_color = "midnightblue"),
    locations = list(
      cells_data(columns = c(1), rows = c(3)),
      cells_data(columns = c(2), rows = c(3)),
      cells_data(columns = c(3), rows = c(3)),
      cells_data(columns = c(4), rows = c(3)),
      cells_data(columns = c(5), rows = c(3)),
      cells_data(columns = c(6), rows = c(3))
    )
  )

```

Graph for Tab 3

```{r}
master_ranks <- read_csv("master_ranks.csv")

master_ranks %>%
    filter(county == input$county1 | county == input$county2) %>% 
    plot_ly(type = 'parcoords',
              line = list(color = ~county), 
              dimensions = list(
                list(range = c(58,1),
                     label = 'Entertainment', values = ~ent_rank),
                list(range = c(58,1),
                     constraintrange = c(5,6),
                     label = 'Night life', values = ~night_rank),
                list(range = c(58,1),
                     label = 'Recreation', values = ~rec_rank),
                list(range = c(58,1),
                     label = 'Health', values = ~health_rank),
                list(range = c(58,1),
                     label = 'Diversity', values = ~div_rank)
              )
      )

```

